// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxQkGVydvMvqXauUplFQcphTfRnP7nEE',
    appId: '1:766809676072:web:c4190722d4e95471b8181d',
    messagingSenderId: '766809676072',
    projectId: 'smart-lab-de7a9',
    authDomain: 'smart-lab-de7a9.firebaseapp.com',
    databaseURL: 'https://smart-lab-de7a9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-lab-de7a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYlx-TqWTQYlrN2B7Ti8SnETzSN4VpIqM',
    appId: '1:766809676072:android:316dea070aa0c031b8181d',
    messagingSenderId: '766809676072',
    projectId: 'smart-lab-de7a9',
    databaseURL: 'https://smart-lab-de7a9-default-rtdb.firebaseio.com',
    storageBucket: 'smart-lab-de7a9.appspot.com',
  );
}
